name: "🏷️ Create release"

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    name: "Create release from CHANGELOG"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (Required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog: CHANGELOG.md